# Generated by Django 6.0.6 on 2026-06-16 00:16

import base.storage
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0002_aulapublicada_progressoaula_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=220, verbose_name='título')),
                ('enunciado', models.TextField(blank=True, verbose_name='enunciado')),
                ('prazo', models.DateTimeField(blank=True, null=True, verbose_name='prazo')),
                ('pontuacao_max', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='pontuação máxima')),
                ('permite_entrega_atrasada', models.BooleanField(default=True, verbose_name='permite entrega atrasada')),
                ('publicada', models.BooleanField(default=False, verbose_name='publicada')),
                ('aula_publicada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to='classroom.aulapublicada', verbose_name='aula publicada')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='classroom.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'atividade',
                'verbose_name_plural': 'atividades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('texto_resposta', models.TextField(blank=True, verbose_name='resposta')),
                ('data_entrega', models.DateTimeField(blank=True, null=True, verbose_name='data da entrega')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('entregue', 'Entregue'), ('atrasada', 'Atrasada'), ('corrigida', 'Corrigida')], default='pendente', max_length=20, verbose_name='status')),
                ('aluno', models.ForeignKey(limit_choices_to={'role': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to=settings.AUTH_USER_MODEL, verbose_name='aluno')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='activities.atividade', verbose_name='atividade')),
            ],
            options={
                'verbose_name': 'entrega',
                'verbose_name_plural': 'entregas',
                'ordering': ['-data_entrega', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EntregaArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('arquivo', models.FileField(storage=base.storage.ProtectedFileSystemStorage(), upload_to='entregas/', verbose_name='arquivo')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='activities.entrega', verbose_name='entrega')),
            ],
            options={
                'verbose_name': 'arquivo de entrega',
                'verbose_name_plural': 'arquivos de entrega',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='atividade',
            index=models.Index(fields=['turma', 'publicada'], name='activities__turma_i_39587b_idx'),
        ),
        migrations.AddIndex(
            model_name='entrega',
            index=models.Index(fields=['atividade', 'status'], name='activities__ativida_a8ecd8_idx'),
        ),
        migrations.AddConstraint(
            model_name='entrega',
            constraint=models.UniqueConstraint(fields=('atividade', 'aluno'), name='unique_entrega_por_atividade_aluno'),
        ),
    ]
