# Generated by Django 6.0.6 on 2026-06-16 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='corrigida'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='corrigido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='corrigido em'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='corrigido_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcoes', to=settings.AUTH_USER_MODEL, verbose_name='corrigido por'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='feedback'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='nota'),
        ),
    ]
