# Generated by Django 6.0.6 on 2026-06-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_entrega_checked_entrega_corrigido_em_and_more'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='anexos',
            field=models.ManyToManyField(blank=True, related_name='atividades', to='materials.material', verbose_name='materiais anexados'),
        ),
    ]
