# Generated by Django 6.0.6 on 2026-06-17 19:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_atividade_anexos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='pontuacao_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='pontuação máxima'),
        ),
    ]
