# Generated by Django 6.0.6 on 2026-06-21 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_atividade_pontuacao_max'),
        ('classroom', '0002_aulapublicada_progressoaula_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('feito', models.BooleanField(default=False, verbose_name='feito')),
                ('feito_em', models.DateTimeField(blank=True, null=True, verbose_name='feito em')),
                ('observacao', models.CharField(blank=True, max_length=280, verbose_name='observação')),
            ],
            options={
                'verbose_name': 'check de atividade',
                'verbose_name_plural': 'checks de atividade',
                'ordering': ['aluno__nome_completo'],
            },
        ),
        migrations.RemoveIndex(
            model_name='entrega',
            name='activities__ativida_a8ecd8_idx',
        ),
        migrations.RemoveConstraint(
            model_name='entrega',
            name='unique_entrega_por_atividade_aluno',
        ),
        migrations.RemoveField(
            model_name='entregaarquivo',
            name='entrega',
        ),
        migrations.AlterModelOptions(
            name='atividade',
            options={'ordering': ['-data', '-created_at'], 'verbose_name': 'atividade', 'verbose_name_plural': 'atividades'},
        ),
        migrations.RemoveIndex(
            model_name='atividade',
            name='activities__turma_i_39587b_idx',
        ),
        migrations.AddField(
            model_name='atividade',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='data'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AddIndex(
            model_name='atividade',
            index=models.Index(fields=['turma'], name='activities__turma_i_d53a60_idx'),
        ),
        migrations.AddField(
            model_name='atividadecheck',
            name='aluno',
            field=models.ForeignKey(limit_choices_to={'role': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='atividade_checks', to=settings.AUTH_USER_MODEL, verbose_name='aluno'),
        ),
        migrations.AddField(
            model_name='atividadecheck',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='activities.atividade', verbose_name='atividade'),
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='corrigido_por',
        ),
        migrations.DeleteModel(
            name='EntregaArquivo',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='anexos',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='aula_publicada',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='enunciado',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='permite_entrega_atrasada',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='pontuacao_max',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='prazo',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='publicada',
        ),
        migrations.AddIndex(
            model_name='atividadecheck',
            index=models.Index(fields=['atividade', 'feito'], name='activities__ativida_940e5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='atividadecheck',
            constraint=models.UniqueConstraint(fields=('atividade', 'aluno'), name='unique_check_por_atividade_aluno'),
        ),
        migrations.DeleteModel(
            name='Entrega',
        ),
    ]
