# Generated by Django 6.0.6 on 2026-08-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_atividadecheck_and_more'),
        ('classroom', '0004_alter_turma_professor'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='atividade',
            name='activities__turma_i_d53a60_idx',
        ),
        migrations.AddIndex(
            model_name='atividade',
            index=models.Index(fields=['turma', 'data', 'created_at'], name='activities__turma_i_8507d0_idx'),
        ),
    ]
