# Generated by Django 6.0.6 on 2026-06-16 00:27

import base.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0002_aulapublicada_progressoaula_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=220, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('arquivo', models.FileField(blank=True, storage=base.storage.ProtectedFileSystemStorage(), upload_to='materiais/', verbose_name='arquivo')),
                ('link_externo', models.URLField(blank=True, verbose_name='link externo')),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('slide', 'Slide'), ('link', 'Link'), ('video', 'Vídeo'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='tipo')),
                ('aula_publicada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais', to='classroom.aulapublicada', verbose_name='aula publicada')),
                ('enviado_por', models.ForeignKey(blank=True, limit_choices_to={'role': 'professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_enviados', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='classroom.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiais',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['turma', 'aula_publicada'], name='materials_m_turma_i_fbc9b2_idx')],
            },
        ),
    ]
