# Generated by Django 6.0.6 on 2026-08-26 01:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_aulapublicada_classroom_pub_turma_order_idx_and_more'),
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['turma', '-created_at'], name='materials_m_turma_i_6b71a5_idx'),
        ),
    ]
