# Generated by Django 6.0.6 on 2026-06-15 20:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=180, verbose_name='nome')),
                ('serie', models.CharField(max_length=80, verbose_name='série')),
                ('ano_letivo', models.PositiveSmallIntegerField(verbose_name='ano letivo')),
                ('codigo_convite', models.CharField(blank=True, editable=False, max_length=12, unique=True, verbose_name='código de convite')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='catalog.disciplina', verbose_name='disciplina')),
                ('professor', models.ForeignKey(limit_choices_to={'role': 'professor'}, on_delete=django.db.models.deletion.PROTECT, related_name='turmas_lecionadas', to=settings.AUTH_USER_MODEL, verbose_name='professor')),
            ],
            options={
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
                'ordering': ['-ano_letivo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data_matricula', models.DateField(default=django.utils.timezone.localdate, verbose_name='data da matrícula')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], default='ativa', max_length=20, verbose_name='status')),
                ('aluno', models.ForeignKey(limit_choices_to={'role': 'aluno'}, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to=settings.AUTH_USER_MODEL, verbose_name='aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='classroom.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'matrícula',
                'verbose_name_plural': 'matrículas',
                'ordering': ['turma__nome', 'aluno__nome_completo'],
            },
        ),
        migrations.AddIndex(
            model_name='turma',
            index=models.Index(fields=['professor', 'ativa'], name='classroom_t_profess_40657c_idx'),
        ),
        migrations.AddIndex(
            model_name='turma',
            index=models.Index(fields=['codigo_convite'], name='classroom_t_codigo__16d234_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['turma', 'status'], name='classroom_m_turma_i_19b874_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['aluno', 'status'], name='classroom_m_aluno_i_1fe7b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('turma', 'aluno'), name='unique_matricula_por_turma_aluno'),
        ),
    ]
