# Generated by Django 6.0.6 on 2026-06-16 00:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('classroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AulaPublicada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ordem_na_turma', models.PositiveIntegerField(default=0, verbose_name='ordem na turma')),
                ('disponivel_em', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora de liberação da aula para a turma.', verbose_name='disponível em')),
                ('publicada', models.BooleanField(default=True, verbose_name='publicada')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicacoes', to='catalog.aula', verbose_name='aula')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas_publicadas', to='classroom.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'aula publicada',
                'verbose_name_plural': 'aulas publicadas',
                'ordering': ['turma', 'ordem_na_turma', 'aula__ordem'],
            },
        ),
        migrations.CreateModel(
            name='ProgressoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('visto_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='visto em')),
                ('concluido', models.BooleanField(default=False, verbose_name='concluído')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('aluno', models.ForeignKey(limit_choices_to={'role': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to=settings.AUTH_USER_MODEL, verbose_name='aluno')),
                ('aula_publicada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='classroom.aulapublicada', verbose_name='aula publicada')),
            ],
            options={
                'verbose_name': 'progresso de aula',
                'verbose_name_plural': 'progressos de aulas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aulapublicada',
            index=models.Index(fields=['turma', 'publicada', 'disponivel_em'], name='classroom_a_turma_i_9828b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='aulapublicada',
            constraint=models.UniqueConstraint(fields=('turma', 'aula'), name='unique_aula_publicada_por_turma'),
        ),
        migrations.AddIndex(
            model_name='progressoaula',
            index=models.Index(fields=['aluno', 'concluido'], name='classroom_p_aluno_i_a3f0fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='progressoaula',
            constraint=models.UniqueConstraint(fields=('aluno', 'aula_publicada'), name='unique_progresso_por_aluno_aula'),
        ),
    ]
