# Generated by Django 6.0.6 on 2026-07-27 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_seed_inteligencia_artificial_turma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'role__in': ('professor', 'admin')}, on_delete=django.db.models.deletion.PROTECT, related_name='turmas_lecionadas', to=settings.AUTH_USER_MODEL, verbose_name='professor'),
        ),
    ]
