# Generated by Django 6.0.6 on 2026-08-26 01:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_aulaimagem'),
        ('classroom', '0004_alter_turma_professor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aulapublicada',
            index=models.Index(fields=['turma', 'ordem_na_turma'], name='classroom_pub_turma_order_idx'),
        ),
        migrations.AddIndex(
            model_name='progressoaula',
            index=models.Index(fields=['aula_publicada', 'concluido'], name='classroom_prog_pub_done_idx'),
        ),
        migrations.AddIndex(
            model_name='turma',
            index=models.Index(fields=['-ano_letivo', 'nome'], name='classroom_turma_year_name_idx'),
        ),
    ]
