# Generated by Django 6.0.6 on 2026-06-15 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('label', models.CharField(max_length=180, verbose_name='nome')),
                ('serie', models.CharField(blank=True, max_length=80, verbose_name='série')),
                ('status', models.CharField(blank=True, max_length=40, verbose_name='status')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('slug', models.SlugField(max_length=120, verbose_name='slug')),
                ('label', models.CharField(max_length=180, verbose_name='nome')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trilhas', to='catalog.disciplina', verbose_name='disciplina')),
            ],
            options={
                'verbose_name': 'trilha',
                'verbose_name_plural': 'trilhas',
                'ordering': ['disciplina__label', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ordem', models.PositiveIntegerField(verbose_name='ordem')),
                ('slug', models.SlugField(max_length=160, verbose_name='slug')),
                ('titulo', models.CharField(max_length=220, verbose_name='título')),
                ('tema', models.CharField(blank=True, max_length=220, verbose_name='tema')),
                ('objetivos', models.JSONField(blank=True, default=list, verbose_name='objetivos')),
                ('prerequisitos', models.JSONField(blank=True, default=list, verbose_name='pré-requisitos')),
                ('modo_origem', models.CharField(blank=True, max_length=80, verbose_name='modo de origem')),
                ('conteudo_html', models.TextField(blank=True, verbose_name='conteúdo HTML')),
                ('conteudo_md', models.TextField(blank=True, verbose_name='conteúdo Markdown')),
                ('html_standalone', models.FileField(blank=True, null=True, upload_to='catalog/html/', verbose_name='HTML standalone')),
                ('status', models.CharField(choices=[('aprovada', 'Aprovada'), ('planejada', 'Planejada'), ('rascunho', 'Rascunho'), ('arquivada', 'Arquivada')], default='aprovada', max_length=40, verbose_name='status')),
                ('versao', models.CharField(blank=True, max_length=80, verbose_name='versão')),
                ('atualizado_em', models.DateTimeField(blank=True, null=True, verbose_name='atualizado em na origem')),
                ('source_path', models.TextField(blank=True, verbose_name='caminho de origem')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aulas', to='catalog.disciplina', verbose_name='disciplina')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aulas', to='catalog.trilha', verbose_name='trilha')),
            ],
            options={
                'verbose_name': 'aula',
                'verbose_name_plural': 'aulas',
                'ordering': ['disciplina__label', 'trilha__label', 'ordem', 'titulo'],
            },
        ),
        migrations.AddConstraint(
            model_name='trilha',
            constraint=models.UniqueConstraint(fields=('disciplina', 'slug'), name='unique_trilha_por_disciplina'),
        ),
        migrations.AddIndex(
            model_name='aula',
            index=models.Index(fields=['status', 'disciplina', 'trilha'], name='catalog_aul_status_5fd1f9_idx'),
        ),
        migrations.AddIndex(
            model_name='aula',
            index=models.Index(fields=['slug'], name='catalog_aul_slug_5c036f_idx'),
        ),
        migrations.AddConstraint(
            model_name='aula',
            constraint=models.UniqueConstraint(fields=('disciplina', 'trilha', 'ordem', 'slug'), name='unique_aula_canonica'),
        ),
    ]
