# Generated by Django 6.0.6 on 2026-06-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/capas/', verbose_name='imagem de capa'),
        ),
    ]
