# Generated by Django 6.0.6 on 2026-07-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_aula_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conceito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('nome', models.CharField(max_length=180, verbose_name='nome')),
                ('disciplina_slug', models.SlugField(blank=True, max_length=120, verbose_name='disciplina')),
            ],
            options={
                'verbose_name': 'conceito',
                'verbose_name_plural': 'conceitos',
                'ordering': ['nome'],
            },
        ),
    ]
