# Generated by Django 6.0.6 on 2026-08-19 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_conceito'),
    ]

    operations = [
        migrations.CreateModel(
            name='AulaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=180, verbose_name='nome do arquivo')),
                ('arquivo', models.ImageField(max_length=255, upload_to='catalog/imagens/', verbose_name='arquivo')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='catalog.aula', verbose_name='aula')),
            ],
            options={
                'verbose_name': 'imagem da aula',
                'verbose_name_plural': 'imagens da aula',
                'ordering': ['aula', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('aula', 'nome'), name='unique_imagem_por_aula')],
            },
        ),
    ]
