# Generated by Django 6.0.6 on 2026-06-16 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=180, verbose_name='título')),
                ('mensagem', models.TextField(verbose_name='mensagem')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='link')),
                ('lida', models.BooleanField(default=False, verbose_name='lida')),
                ('tipo', models.CharField(choices=[('aula', 'Aula'), ('atividade', 'Atividade'), ('prazo', 'Prazo'), ('correcao', 'Correção')], max_length=20, verbose_name='tipo')),
                ('dedupe_key', models.CharField(blank=True, editable=False, max_length=180, verbose_name='chave de deduplicação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', 'lida', '-created_at'], name='notificatio_usuario_304d0a_idx'), models.Index(fields=['usuario', 'tipo'], name='notificatio_usuario_27a729_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('usuario', 'tipo', 'dedupe_key'), name='unique_notificacao_dedupe_por_usuario')],
            },
        ),
    ]
